repository_type: pipeline
nf_core_version: 2.14.1
lint:
  actions_ci: False
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-aggregate_logo_light.png
    - conf/igenomes.config
    - docs/images/nf-core-nf-aggregate_logo_dark.png
    - docs/images/nf-core-nf-aggregate_logo_light.png
  files_unchanged:
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-aggregate_logo_light.png
    - docs/images/nf-aggregate_logo_dark.png
    - docs/images/nf-aggregate_logo_light.png
  multiqc_config:
    - report_comment
  nextflow_config:
    - custom_config
    - manifest.homePage
    - manifest.name
    - process.cpus
    - process.memory
    - process.time
  schema_lint: False
  pipeline_name_conventions: False
template:
  prefix: seqeralabs
  skip:
    - ci
    - igenomes
    - nf_core_configs
